apiVersion: v1
kind: Pod
metadata:
  name: db
  labels:
    name: db
spec:
  containers:
  - name: db
    image: mongo
    command: ["mongod"]
    args: ["--rest", "--httpinterface"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 27017
