apiVersion: v1
kind: Pod
metadata:
  name : nginx
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
    ports: 
    - containerPort: 80

    